let express=require("express")
let mongoose=require("mongoose")
let cors=require("cors")
const route = require("./route/userrt")
mongoose.connect("mongodb://127.0.0.1:27017/swamy").then(()=>{
    console.log("c k")
})
let app=express()
app.use(express.json())
app.use(cors())
app.use("/",route)
app.listen(5000)